name: flutter_starter_project
description: A project created in flutter using MVVM architecture & GetX. It supports both android and iOS.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # adding get for state management
  get: ^4.6.5
  # adding http for network calls
  http: ^0.13.5
  # adding get_storage for storing user session data
  get_storage: ^2.1.1
  # adding flutter_dotenv for managing different environments and flavors in our app
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # registering assets into our app
    - assets/
    - assets/images/
    - assets/icons/
    # registering env files into our app
    - .env.development
    - .env.production

  
  # To add fonts to your application, add an font like this:
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
    
    - family: poppins_semibold
      fonts:
        - asset: assets/fonts/poppins_semibold.ttf

